### ISSUE TITLE
Refonte du système de statistiques

### ISSUE THREAD

**Issue by DraftProducts** [DraftProducts/blagues-api#198]
Pour le nouveau système de statistiques, il est prévu de donner plus ou moins de points en fonction de l'appréciation de la blague. Chaque action donne un certain nombre de points. 

### Système de points

| Action      | Points      |
|------------|-----------|
| Proposition d'une blague | +10 points |
| Correction d'une blague | +7 points |
| Approbation d'une blague* | +4 points |
| Désapprobation d'une blague* | +4 points |
| Vote d'une blague via une réaction** | +2 points |

\* Points pour l'approbation d'une blague pour un parrain.
\*\* Les votes via réactions ne seront pas comptabilisés pour les parrains.

**Points bonus :**
| Action      | Points      |
|------------|-----------|
| Approbation d'un parrain | +2 points |
| Désapprobation d'un parrain | -2 points  |
| Vote d'un membre positif | +1 point |
| Vote d'un membre négatif | -1 point  |

**Comment by saphirrc** [comment]
Pour le nouveau système de stats, il est prévu de donner plus ou moins de points en fonction de l'appréciation de la blagues. Chaque action donne un certain nombre de points. 
_Le contenu entre parenthèse représente le nombre de points_

- [ ] Adapter la base de données pour ajouter les réactions
- [ ] Nombre de blagues ajouté (10), corrigé(7)
- [ ]  Parrain: approuvé(4), désapprouvé(4)
- [ ] Votes de membres(2) _Les votes de parrain avec les réactions ne seront pas comptabilisé_
- [ ] Appréciation de la blague _pointage pour la personne ayant suggérer la blague ou la modification_. Un vote de parrain positif ajoute deux point et un négatif retire deux point. Un vote de membre positif ajoute un point et retire un point pour un vote négatif. 
- [ ] pointage total
