### ISSUE TITLE
Problème lors de l'approbaion d'une blague

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#204]
Petit truc, totalement logique mais pas très pratique, on ne peut pas approuver une blague après y avoir fait une correction, vu qu'il faut approuver cette correction mais qu'on ne peut pas approuver les siennes. Exemple pour être plus clair : La blague c'est "bananne", je la corrige en "Banane", et après je ne peux pas l'approuver.

**Comment by DraftProducts** [comment]
Ce système a été mis en place afin d'éviter que des blagues soient ajoutées à l'API avec des fautes.
