### ISSUE TITLE
Ajouter CORS

### ISSUE THREAD

**Issue by matiaschileno** [DraftProducts/blagues-api#234]
L'API n'accepte pas des requêtes Cross Origin. Serait-il possible d'ajouter https://github.com/fastify/fastify-cors ? Sur un ancien commit (quand l'API était sur express: https://github.com/Blagues-API/blagues-api/commit/0a6af8d84e5eff438639a1e36d5f2f6a8e0185d7) vous l'aviez déjà ajouté mais depuis la refonte ce n'est plus le cas. Merci.

**Comment by DraftProducts** [comment]
Je m'en occupe ! Merci pour l'issue 👍

**Comment by DraftProducts** [comment]
C'est en production 👍

**Comment by matiaschileno** [comment]
Super, merci pour la réactivité @DraftProducts  !
