### ISSUE TITLE
Pouvoir approuver les blagues malgré correction en cours

### ISSUE THREAD

**Issue by Proryon** [DraftProducts/blagues-api#243]
Je vous propose que lorsqu'une blague a une correction, au lieu d'être bloqué par la correction qu'on puisse tout de même l'approuver & prévienne qu'une correction est en cours.

**Comment by DraftProducts** [comment]
Le souci avec ça, c'est qu'on publiera une blague avec des fautes.
À la limite, on peut bloquer uniquement la dernière approbation, mais selon moi il faut garder le blocage.

**Comment by Proryon** [comment]
Après c'est juste agaçant de ne pas pouvoir voter une blague. Au pire on peut suivre ton idée qui est bonne au final. Au moins ça nous arrêtes pas trop

**Comment by coco875** [comment]
Après tu peux rajouter une sorte d'étape ou c'est validée en attente de la fin de la correction

**Comment by DraftProducts** [comment]
J'aime bien l'idée ✌️

**Comment by Proryon** [comment]
Why not ? Bonne idée.
