### ISSUE TITLE
[Feature] Moyen d'obtenir l'id d'une blague en passant par le bot

### ISSUE THREAD

**Issue by Zuruuh** [DraftProducts/blagues-api#313]
Quand on récupères une blague avec le bot et qu'on aimerais y ajouter une correction, on a aucun moyen de trouver l'id de la blague en question pour faire la suggestion. Un simple fix serait juste d'ajouter en bas de l'embed de la blague son id

**Comment by ErwanGit** [comment]
Tu peux obtenir l'identifiant d'une blague en activant le mode développeur sur ton Discord, puis en réalisant un clique droit, copier l'identifiant 

https://docs.draftbot.fr/autres/recuperer-un-identifiant#message

**Comment by Zuruuh** [comment]
Le soucis c'est que le bot ne trouve pas les blagues déjà acceptées avec l'id d'un message crée avec un /blague. Par contre, quand on récupère une blague directement depuis l'api (donc on obtient son id), on peut correctement créer une correction.

**Comment by DraftProducts** [comment]
Ouip, compris, je suis d'accord 👍
Une amélioration de la commande `/blague` est nécessaire.
