### ISSUE TITLE
Bump la version de node du dockerfile

### ISSUE THREAD

**Issue by Zuruuh** [DraftProducts/blagues-api#317]
La version 16.14 de node n'est plus dispo sur le docker hub, donc ce serait pas mal de migrer sur la version 16.15. (À l'heure actuelle le script dev:build fail à cause de ça)

Edit: my bad le soucis venais de moi, desolé pour le désagrément

**Comment by DraftProducts** [comment]
Salut @Zuruuh on a bump vers la `18.1` :v:
