### ISSUE TITLE
Certains éléments de l'embed retiré lors de la validation d'une correction

### ISSUE THREAD

**Issue by ErwanGit** [DraftProducts/blagues-api#323]
La validation finale d'une correction retire la couleur et l'auteur de l'embed de la blague qui est suggérée ![image](https://user-images.githubusercontent.com/24718500/173933423-9d7e4041-33b5-43ea-9d5f-4f6fa8faf14f.jpeg)

**Comment by DraftProducts** [comment]
Erreur survenue de l'intent des messages désactivé sur le panel
