### ISSUE TITLE
Boutons toujours utilisables lors de l'étape de correction d'une blague.

### ISSUE THREAD

**Issue by DraftProducts** [DraftProducts/blagues-api#331]
![image](https://user-images.githubusercontent.com/29425008/174634637-4d063417-007c-4773-b71b-d4981ecb6fad.png)

Il faudrait retirer les boutons afin de faire comprendre qu'ils ne sont plus utilisables.
Bonus : 
 - Ajouter des boutons sur le nouveau message
 - Ajouter la partie qu'on modifie en \`\`\` code \`\`\` pour pouvoir copier/coller facilement (dans un embed ?).

**Comment by swiizyy** [comment]
🤔 Peut être juste désactiver les boutons pendant le requestChange et une fois l'etape fini ou annulé a cause tu timeout les réactiver ?

**Comment by DraftProducts** [comment]
Les désactiver revient à la même chose que les supprimer 🤔 
Mais en soit oui ça permettra d'éviter le problème.
