### ISSUE TITLE
Proposition de endpoint

### ISSUE THREAD

**Issue by plumedours** [DraftProducts/blagues-api#333]
Serait-il possible d'avoir des endpoints : 
- soit pour obtenir toutes les blagues d'un coup
- soit obtenir le nombre total de blague
- soit avoir des filtres par types, pour obtenir toutes les blagues d'un type (merci Zuruh)

**Comment by DraftProducts** [comment]
Salut @plumedours :v:

Le nombre de blagues est déjà obtenable via un endpoint non documenté : `GET /api/count`.

Pour ce qui est des autres proposés, pour l'instant j'aurais tendance à m'y opposer pour deux raisons :
 - Récupérer toutes les blagues ou seulement d'un type n'a pas vraiment d'intérêt et cela sort d'un cas d'usage d'une API.
 - En termes de réseau, tout récupérer est très désavantageux et très lent compte tenu de la taille du contenu.
