### ISSUE TITLE
Refonte de la commande stats (global)

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#358]
Je propose la refonte de la commande stats pour compléter l'issues #198  :
- Celle ci serais sous forme de page.
- Un maximum de 25 utilisateurs par page.
- Changer de pages via des boutons ( <= | - | => )

**Comment by achille-bsc** [comment]
perso je trouve que c'est une bonne idée, et je propose même de m'en occuper si vous voullez @DraftProducts ou @ErwanGit

**Comment by DraftProducts** [comment]
Yes j'aime bien l'idée 👍 
Essayez de voir avec @saphirrc pour bosser en corrélation avec lui, c'est lui qui avait été assigné à cette refonte de statistiques :v:
Si @Swiizyy & @saphirrc ne souhaitent pas s'en charger, on pourra te l'assigner stv @achille-bsc.
