### ISSUE TITLE
Amélioration de la commande (stats user)

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#360]
Je propose une amélioration de la commande (stats user) pour les issues #198 et #356 .Voici trois models :
Model 1:
![model-1](https://user-images.githubusercontent.com/52933626/175232070-2126e085-f3c9-401f-8d60-8e117f6680dd.PNG)
Model 2:
![model-2](https://user-images.githubusercontent.com/52933626/175232068-1749ee59-d06e-4064-99d7-1c905f957a26.PNG)
Model 3:
![models-3](https://user-images.githubusercontent.com/52933626/175232064-7c2530f7-ab67-4414-a7de-ffc66aa1cbff.PNG)

**Comment by achille-bsc** [comment]
perso j'ai une préférence pour le model n°1, mais il faudrais quand même y ajouter les décisions de Parrain malgrès tout... donc je proposerais de faire un mélange du 1 et du 3 🤔

**Comment by swiizyy** [comment]
Les décisions du parrains sont sur le model 1 c'est les approbations et désapprobations @achille-bsc

**Comment by achille-bsc** [comment]
Ah oui, pardon 😅 c'est juste que c'était un peut moins visible, mais okk je voit ! Perzo je valide à fond le modèle 1

**Comment by swiizyy** [comment]
En gros si il est parrain les case Approbations et Désapprobation seront visible sinon non

**Comment by DraftProducts** [comment]
Perso j'aime bien le modèle 3 🤔
Il sera plus facile à dev, car on pourra isoler le field 3 pour les parrains.
Les deux premiers seront donc toujours les mêmes pour tous les utilisateurs.

**Comment by swiizyy** [comment]
En sois les trois ne sont pas compliquée a dev @DraftProducts 
Mais oui j'ai également une préférence pour le 3 🙂
