### ISSUE TITLE
Ameliorations des commandes stats

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#361]
Je propose de séparer la commande en deux commands :
- 1 = leaderbord => Affiche les toutes les statistiques 
- 2 = stats => Affiche les stats de l'utilisateur/d'un utilisateur

**Comment by achille-bsc** [comment]
ce serait plutôt inutile vu qu'on à déjà la possibilitée de voir les stats d'un utilisateur en particulier sous forme de userOption facultatif

**Comment by swiizyy** [comment]
beh si une personne veut passer par cette commandes elle pourras 🤷‍♂️ je voulais mettre sa avant que tu mette la commande en contextmenu mais j'avais oublier

**Comment by swiizyy** [comment]
sinon dans se cas on enlève la partie user comme y'aura le contextmenu mais j'aurais bien fait mon choix 2 perso

**Comment by swiizyy** [comment]
Quand pense tu @DraftProducts ?

**Comment by swiizyy** [comment]
En plus @achille-bsc c'est très facile à intégrer pour le coups avec les fonctions dans l'autres fichier 🙂

**Comment by DraftProducts** [comment]
Je suis pas fan du choix 2 ça dédouble juste les commandes.
Et je suis pas fan non plus de laisser que le context menu parce que ça veut dire qu'on ne peut pas afficher les stats via une mention, il faut que le context menu soit que du bonus.

**Comment by achille-bsc** [comment]
Ah oui ok, je voit... bah ouais... ça poura être modif rapidement avec les fonctions que j'ai fais du coup

**Comment by swiizyy** [comment]
@DraftProducts et le choix 1 tu en pense quoi ?

**Comment by DraftProducts** [comment]
Ah j'avais mal lu le choix un

**Comment by DraftProducts** [comment]
A la limite oui 👍

**Comment by swiizyy** [comment]
Super alors 😁

**Comment by achille-bsc** [comment]
Personnellement, je serais plus d'avis de laisser comme c'est actuellement. Je ne pense pas que ce soit nécessaire de modifier le design de la commande qui est déjà très simple d'utilisation comme ça... ça ne ferait que rajouter des commandes à la liste de commandes du bot, de mettre des sous-commandes…
