### ISSUE TITLE
Amélioration du module reminders

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#362]
Quelques amélioration: 
- Le titre passe en nom de l'auteur + Icon du bot
- Un nouveau titre qui changera de typo dynamiquement 
- Fix du footer qui s'afficher pas si il y avais seulement une page
- Si il y a plus de deux page l'icone du bot s'affiche dans le footer

**Comment by DraftProducts** [comment]
L'issue sert juste à parler de la fonctionnalité avant son développement.
Si tu as déjà fait la PR l'issue est inutile.
