### ISSUE TITLE
Utilisation des modals

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#364]
Vu qu'assez récemment (je crois) les modals sont sortis, et que je trouve que ça aiderait très bien pour le système de corrections, je propose de les y ajouter.

  Ce que je veux dire par là, c'est qu'actuellement, il faut des intents pour les messages, et à propos de messages, contrairement aux suggestions, quand quelqu'un veut faire une correction, des messages inutiles sont envoyés dans le #commandes. En plus, j'ai vu très peu de bots utiliser cette feature, et c'est dommage, mais en même temps ça ferait passer Blagues API comme un bot encore mieux que ce qu'il ne l'est déjà 😁. 

  Avec ça, plus aucun souci à propos des messages ! Les récents problèmes où la couleur et l'avatar customisés de l'EMBED disparaissaient ne seraient plus qu'un mauvais souvenir. Enfin j'espère.

**Comment by DraftProducts** [comment]
Le souci a déjà été corrigé et j'ai déjà check, le système de modal que Discord propose ne répond pas encore aux besoins pour le système de corrections, en plus on l'a entièrement refait il est beaucoup mieux mtn.
