### ISSUE TITLE
Soucis de grammaire divers

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#367]
J'ai vu quelques soucis de grammaire ici et là, je les report ici.

> Quand on envoie une suggestion, "La blague à été envoyée". Il n'y a pas d'accent sur le "a".
> Sur l'EMBED des #suggestions et #corrections, "Elles sont toutes issues de ce salon proposées par la communauté.". Je trouve ça assez facile à mal interpréter. Il faudrait ajouter une virgule juste après "salon".
> Dans la description du #suggestions, "Pensez a respecter le format, sans quoi elles ne seront pas acceptées". Il faut, cette fois, un accent sur le "à".
> Pour chipoter, vu que "API" est écrit en majuscules partout, surtout dans le nom du bot, peut-être changer la description des deux précédents salons : "pour les retrouver dans l'api", "que vous trouvez dans l'api" : "dans l'API"

**Comment by achille-bsc** [comment]
Pour le premier report, ça a déjà été corrigé dans le code 😉
Pour le deuxième, je serais plus d'avis de mettre "et" au lieu d'une virgule, ça renforcera la compréhension du sens de la phrase.
Pour la 3ᵉ chui d'accord il faudra régler ça @DraftProducts 🙃
et pour la dernière je ne vois pas de quoi vous voulez parler 😓

**Comment by MrPRAINGLE** [comment]
Dans la description des salons Discord #suggestions et #corrections, on retrouve respectivement  "pour les retrouver dans l'api" et "que vous trouvez dans l'api". Or le nom du bot et de l'API c'est "Blagues API" et non "Blagues api", donc ce que je suggère c'est de changer "api" en "API".
Et en passant, tutoie-moi stp 😅

**Comment by achille-bsc** [comment]
Ah, okk j'avais pas compris 😅 mais après la différence c'est que Blagues-API c'est le nom de l'api... c'est pour ça que c'est écrit avec une majuscule partout... donc je ne sais pas si ce serait obligatoire de le mettre en majuscule dans ce contexte 🤔 mais en soit c'est vrai que c'est pas impossible 👍

**Comment by MrPRAINGLE** [comment]
Bah le fait est que "API" c'est un acronyme donc ça devrait d'office être en majuscule.
