### ISSUE TITLE
Pourquoi un field ?

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#368]
Sur l'embed des `/stats`, dans tous les cas, il y a un field "Statistiques globales". Ce qui voudrait dire qu'il aurait un autre field, mais il n'est disponible que pour les parrains. Je trouverais donc plus logique de juste mettre une description à l'EMBED plutôt qu'un field si le membre à afficher les statistiques n'est pas parrain.

**Comment by achille-bsc** [comment]
Le système de statistiques est en train d'être refait, j'ai moi-même revu le design (suite à une suggestion de @Swiizyy) qui sera désormais refait de A à Z 🙃
