### ISSUE TITLE
Statistiques "à long terme"

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#376]
Je propose un truc pour compléter l'issue #198, ça serait que l'activité dans le serveur soit prise en compte dans les statistiques. Ce serait pas beaucoup, mais par exemple à chaque mois d'inactivité (pour faire large) des points soient retirés des statistiques, ou ajoutés en bonus.

Par exemple, si le membre est actif, des points (jusqu'à, allez... 50) peuvent s'ajouter aux statistiques sous la forme de "Activité sur le serveur"

Ah aussi, peut-être essayer de comptabiliser l'activité Github aussi, dans la même catégorie (elle deviendrait donc "Activité sur le projet") ou sur une autre qui serait "Activité sur le Github".

**Comment by DraftProducts** [comment]
> A chaque mois d'inactivité (pour faire large) des points soient retirés des statistiques.

Peut-être diminuer la valeur des points en fonction de la date de l'action ?
`Day 0 < x < 2 mois` : x1
`2 mois < x < 6 mois` : x0.75
`6 mois < x < Infini` : x0.5

> Si le membre est actif, des points (jusqu'à, allez... 50) peuvent s'ajouter aux statistiques sous la forme de "Activité sur le serveur"

Je ne suis pas trop pour, ça n'a pas vraiment de lien avec l'api, l'activité sur le serveur peut être vue avec le système de niveaux de DraftBot, je ne suis pas trop pour dupliquer un système pareil.

> Comptabiliser l'activité GitHub

Là aussi je ne suis pas trop pour, ça donnerait un trop gros avantage, notamment à moi, je suis l'auteur de plus de 90% des commits du projet et en soi ça n'a pas vraiment de lien avec le système de blagues.

**Comment by DraftProducts** [comment]
Qu'entends-tu par "activité" ? Nombre de messages envoyés ?
