### ISSUE TITLE
Ajout d'un /report pour les doublons

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#377]
Personnellement, je trouve ça assez relou de partager les ID des blagues doublons pour que Draft les supprime. C'est long, pas hyper pratique, et ça doit sûrement prendre sur son temps.

  Donc je me dis, en ajout de la refonte du système de suggestions, pourquoi pas ajouter un `/report` ? Avec un nouveau salon et tout et tout, ça fonctionnerait pareil que les blagues / corrections mais ça ne rapporterait que 5 points, et le salon serait réservé au parrains (ça ne sert à rien aux membres de connaître les doublons).

  Les membres auront juste à faire un `/report <ID1> <ID2>` pour qu'un EMBED contenant les deux blagues soit envoyé dans un salon #doublons. Vous en pensez quoi ?

**Comment by DraftProducts** [comment]
J'aime bien l'idée, mais je pense que nous pourrions aller plus loin et l'amener vers une commande qui permet la suppression d'une blague avec plusieurs raisons possibles.
`/report <ID> <Raison> <Information supplémentaire>`

**Comment by MrPRAINGLE** [comment]
Pas bête, mais faudrait toujours une approbation des parrains du coup

**Comment by DraftProducts** [comment]
> Pas bête, mais faudrait toujours une approbation des parrains du coup

Oui 👍

**Comment by DraftProducts** [comment]
Superseded by #424, which remove useless features and includes requested changes.
