### ISSUE TITLE
Impossibilité de voir les statistiques globales (voulu ?)

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#379]
Tout à l'heure, j'ai fait un ptit `/stats` comme ça et... Le `/stats` sans choisir d'options `user` renvoie les stats de l'auteur de la commande et plus les statistiques globales.

C'est voulu ou pas ? C'était drôlement pratique pour se repérer... C'est en lien avec le nouveau système de suggestions ?

**Comment by achille-bsc** [comment]
C'est tout simplement par ce que les statistiques globales ont été transférés sur la commande "/leaderbord " ave cun système de pagination
