### ISSUE TITLE
Ne plus encombrer les salons suggestion/correction

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#386]
Je propose de désencombré ces salons en supprimant les messages au moment ou celle ci sont migré ou non migré sa ferais beaucoup moins de message dans le salon est de toute façon il y'a le salon logs qui les regroupe tous ..
Cela permettrais au membre de pas remonter 300 blagues migré ou pas pour ajouté un emoji a une blague et permettrais d'avoir des salons beaucoup plus propres 😄

**Comment by MrPRAINGLE** [comment]
Je suis d'accord, mais dans ce cas-là faudrait ajouter un salon #refus par exemple. Si jamais on retrouve de bons éléments.

**Comment by swiizyy** [comment]
@MrPRAINGLE Tout est déjà stocker dans les logs

**Comment by swiizyy** [comment]
@DraftProducts Tu en pense quoi ?
Le seul point négatif je pense sa serais qu'on ne puisse pas remonter les messages avec le lien qui va mener vers le log mais au pire on pourrais toujours faire un bouton remonter avec le lien du message supprimé nan ?

**Comment by DraftProducts** [comment]
Je ne suis pas trop pour, l'historique des blagues représente l'ensemble du travail de la communauté, mais aussi son ancienneté.
C'est ce qui justifie le nombre de blagues actuel sur l'api.

**Comment by swiizyy** [comment]
Au pire on peut le faire mais garder le salon en temps qu'archive ou tout le monde pourra aller voir. 

Car les salons ne font pas du tout propres comme il le sont actuellement et se serais plus simple pour les membres de votés pour une blagues quand celle ci n'est pas pas 200 blagues plus haut car il n'ont aucun moyen de faire remonter les message automatiquement contrairement au parrains.

**Comment by swiizyy** [comment]
Cela donnerais que tu positifs de mon point de vue

**Comment by DraftProducts** [comment]
Si on avait fait ça au lancement du projet pourquoi pas, hors là il y a un grand nombre de blagues déjà présentes, je ne vois pas comment tu voudrais faire la migration.

**Comment by swiizyy** [comment]
Justement je te propose de faire une catégorie archive ou tu mettras les salon actuel et d'en refaire d'autre au propres après.
Comme ca on aura toujours accès au ancienne blagues

**Comment by swiizyy** [comment]
Du coup Nico pour cette PR ?

**Comment by DraftProducts** [comment]
Compte tenu de ce qui a été dit plus haut, je ne suis pas trop pour, ça rajoutera des salons, le système actuel me semble déjà suffisant.
