### ISSUE TITLE
Améliorer le sticky messages

### ISSUE THREAD

**Issue by swiizyy** [DraftProducts/blagues-api#387]
Pourquoi ne pas relancer les stickys message quand il y'a une blague d'ajouté cela permettrais d'avoir toujours le bon nombre de blagues d'indiqué ? 
Ce n'est pas grand chose mais sa serais toujours un plus je pense 🤷‍♂️

**Comment by DraftProducts** [comment]
Je trouve que c'est une bonne idée 👍

**Comment by swiizyy** [comment]
Il va falloir revoir le système mais c'est jouable 🙂
