### ISSUE TITLE
Correction message

### ISSUE THREAD

**Issue by achille-bsc** [DraftProducts/blagues-api#394]
Hello 👋 !
Je pensais que ce serait peut-être plus cohérent de mettre le message de confirmation lors de la proposition d'une correction en éphémère, comme pour le message de suggestion. Ou alors passer celui de suggestion en message non-éphémère... 🤷 comme vous préférez 🙃 

<img width="474" alt="Capture d’écran 2022-07-08 à 03 41 25" src="https://user-images.githubusercontent.com/82178406/177899917-83eb3bb9-f5a4-4679-b0e8-9c79d9de0152.png">

**Comment by DraftProducts** [comment]
C'est ok pour moi, je dirais de tout passer en éphémère et d'améliorer le message de suggestion avec "proposition d'une".

**Comment by swiizyy** [comment]
Je suis carrément pour bien jouer pour cette idée Achille !

**Comment by Swiizyy** [comment]
@achille-bsc, Je vais te laisser faire une PR pour cette amélioration. Je ne vais pas la faire, le but n'est pas que je fasse personnellement toutes les PR possibles en un temps record et de ne laissez participer personne. 🤞

**Comment by swiizyy** [comment]
@DraftProducts En faite y'a meme pas besoin grace aux modifs que tu a fait dans utils

**Comment by DraftProducts** [comment]
Bon bah on peut close alors ✌️
