### ISSUE TITLE
Auto-publication des blagues chaque semaine sur GitHub

### ISSUE THREAD

**Issue by DraftProducts** [DraftProducts/blagues-api#398]
Nous pourrions réfléchir à un système pour auto-publier les blagues sur GitHub chaque dimanche (par exemple) s'il y en a de nouvelles, ça permettrait de les synchroniser automatiquement.

**Comment by swiizyy** [comment]
Ouais sa serais pas mal :) 
Peut-être faire un script sh avec toute les commandes git qu'il faut et l'exécuter au moment on en aura besoin.
Au build peut être lancer un script qui nous connectera a GitHub avec un token dans le .env
Au demarrage peut être lancer un Timeout et dans celle ci vérifier si le jour choisi est le bon et si il y'a des modifs dans le fichier appeler le script sh.

Je sais pas si tu vois se que je veut dire 😅

**Comment by DraftProducts** [comment]
Oui je vois ce que tu veux dire mais je pense que ce serait plus stylé de dev un truc avec l'api GitHub 🤔

**Comment by swiizyy** [comment]
comment sa ?🤔

**Comment by DraftProducts** [comment]
https://stackoverflow.com/questions/11801983/how-to-create-a-commit-and-push-into-repo-with-github-api-v3
https://github.com/azu/git-commit-push-via-github-api

Voici de la doc pour illustrer ce dont je parle.

**Comment by swiizyy** [comment]
Ohhhh trop classe 😮

**Comment by swiizyy** [comment]
Vasy je tente de faire un truc se soir si tu est d'accord

**Comment by swiizyy** [comment]
@DraftProducts tu peux finalement te l'assigné, malheureusement je ne vais vraiment pas avoir le temps à partir d'aujourd'hui.

**Comment by DraftProducts** [comment]
On va la laisser ouverte au cas où quelqu'un serait intéressé 👍

**Comment by achille-bsc** [comment]
Hello ! je pense avoir finit le PR sur les nameLocalization ! si vous la validez, je veux bien tenter de m'en occuper ! j'ai déjà commencé à regarder un peut... et ça à l'air faisable en vrai 🤔

**Comment by DraftProducts** [comment]
Alors, on part là-dessus 😎

**Comment by achille-bsc** [comment]
Étant donné que le merge des blagues sur github concerne l'entièretée de l'api, je le fais ou le système ? dans le dossier bot ?

**Comment by achille-bsc** [comment]
Ce soir je lance la pr pour que vous puissiez commencer à faire un début de review

**Comment by achille-bsc** [comment]
je peut  fermer l'issue du coup ou pas vu que je crois que le code à été  merge vu que je voit plus la PR....

**Comment by DraftProducts** [comment]
What ? Non rien n'a été merge, il n'y a plus la moindre trace de la branche 🤔

**Comment by DraftProducts** [comment]
Il a du supprimer son fork 🤔

**Comment by swiizyy** [comment]
Il n'y a jamais eu de PR pour cette issue il me semble 🙂

**Comment by DraftProducts** [comment]
En effet, je crois que je l'ai confondue avec #416 🤔

**Comment by DraftProducts** [comment]
Ta branche existe bel et bien @achille-bsc https://github.com/Blagues-API/blagues-api/tree/feat/joke-aut-publication, je crois que tu n'as juste jamais créé de PR.

**Comment by achille-bsc** [comment]
Ah ok, je croyais que si... bah je fais ça se soir en rentrant ou demain aprem...
