### ISSUE TITLE
Pouvoir ignorer des types de blagues en tant que parrain

### ISSUE THREAD

**Issue by ErwanGit** [DraftProducts/blagues-api#408]
Ajouter la possibilité de pouvoir ignorer certains types de blagues en tant que parrain pour éviter notamment d'être mentionné pour l'approbation des corrections/suggestions des blagues dont le type est ignoré.
On peut également faire en sorte que lorsque l'on appuie sur le bouton "Mes propositions", les blagues ignorés soient affichée, mais qu'elles soient barrées.

La configuration de cela se ferrait via une commande Slash, par exemple `/ignore` avec comme paramètre les types de blagues actuellement disponible sur Blagues API et qui serait réservée aux parrains leur permettant de désactiver ou réactiver un type de blague à n'importe quel moment.

**Comment by swiizyy** [comment]
Vraiment une très bonne idée 👍🏼

**Comment by achille-bsc** [comment]
Moi je peut m'en occuper si ya personne qui le fais 🤷 c'est vrai que ce serait pratique...
Je promet pas que ce sera fais ultra rapidement mais bon 😓

**Comment by DraftProducts** [comment]
> Moi je peut m'en occuper si ya personne qui le fais 🤷 c'est vrai que ce serait pratique...
> 
> Je promet pas que ce sera fais ultra rapidement mais bon 😓 

Si tu veux ✌️
Suffit que tu demandes a @Zuruuh l'accès à son repo.
