### ISSUE TITLE
Changer la règle de vote d'une blague ayant une correction en cours

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#418]
Lorsqu'une blague a une correction en cours et qu'elle n'a pas été ajoutée ou refusée, on ne peut pas l'approuver sans approuver la correction ou la désapprouver sans désapprouver la correction. Mais et si la correction ne nous convient pas ? On la désapprouve. Et si la blague est bien, on ne peut pas l'approuver. C'est dommage, il faudrait faire en sorte que si l'on veuille donner son avis sur une suggestion, notre avis sur la correction ne compte pas.

**Comment by swiizyy** [comment]
@DraftProducts Tu en pense quoi ?
Je suis a 50/50 sur cette ajouts 😕

**Comment by DraftProducts** [comment]
Perso je suis pour cet ajout, il n'a pas tord 👍

**Comment by swiizyy** [comment]
@MrPRAINGLE Tu peut en faire une PR ou alors un commit sur la PR #415 car se n'est pas grand chose du tout .

**Comment by DraftProducts** [comment]
Sur une PR à part svp, ce serait bien de la merge.
