### ISSUE TITLE
Aperçu du /leaderboard

### ISSUE THREAD

**Issue by achille-bsc** [DraftProducts/blagues-api#421]
Sur la commande /leaderboard je pense que ce serait une bonne idée de mettre en gras la ligne qui correspond à l'utilisateur ayant fais la commande. Cela permettrais de faciliter la lecture de notre propre classement car la plupart du temps, on met un peut de temps à se trouver pour savoir combien on est dans le classement.

**Comment by swiizyy** [comment]
J'aurais peut etre mis un sa plus un indicateur genre `>` pour mieux le voir

**Comment by achille-bsc** [comment]
Ouais pourquoi pas, ou sinon les deux... jsp, je voullais déjà savoir si l'idée étais bonne ou non 🙃

**Comment by swiizyy** [comment]
Ouaip 👍🏼
Si tu veut t'en occuper fait une PR :)

**Comment by achille-bsc** [comment]
La chui pas chez moi, donc je peut pas le faire dans l'immédiat, mais j'aimerais bien m'en occuper 😅 on peut attendre la semaine pro ou pas ?
Sinon occupes-t-en si tu veux 🙃😉

**Comment by DraftProducts** [comment]
C'est bon pour la semaine pro :v:

**Comment by achille-bsc** [comment]
> C'est bon pour la semaine pro :v:

Cool ! Merci ^^
