### ISSUE TITLE
Recherche dans les blagues par mot-clé

### ISSUE THREAD

**Issue by MrPRAINGLE** [DraftProducts/blagues-api#425]
Aah, quoi de plus rageant que de ne pas avoir de catégorie chuck norris... Et si on veut des blagues sur Hitler ? Les chats ? Le p'tit Gregory ? On pourrait faire une commande pour rechercher une blague ou liste de blagues par mot-clé !

**Comment by achille-bsc** [comment]
L'idée est vraiment bonne ! il faudrait en plus juste s'inspirer du système fait dans la commande "correction" et "delete" (enfin la fonction utilisée pour ça ⇒ "findJoke()") et la remettre sous forme de route dans l'api… Tu veux t'en occuper ? Sinon, chui pas sûr d'être capable de le faire... mais je pourrais au moins essayer, d'autant plus que c'est intéressant de toucher directement à l'api.

**Comment by MrPRAINGLE** [comment]
Je veux bien !! Juste, je préfère avoir confirmation de quelqu'un d'autre avant de me lancer dans un truc comme ça... Vu que t'es le seul à avoir répondu, je sais pas si les autres pensent que c'est une bonne idée

**Comment by swiizyy** [comment]
Je trouve que c'est une bonne idée 👍

Juste à attendre l'avis de DraftMan 🙂

**Comment by DraftProducts** [comment]
Je vois l'intérêt que ça pourrait avoir, mais je ne suis pas forcément client de ce genre de commande, du moment que cette idée motive quelqu'un, que c'est bien fait et réfléchi, c'est good pour moi 👍

**Comment by MrPRAINGLE** [comment]
Je m'en charge ! :)

**Comment by DraftProducts** [comment]
Si tu penses que tu es en mesure de mener cette idée à terme, c'est d'accord.
Tu as laissé en plan la dernière PR pendant 2 mois et j'ai dû m'en charger 🤷‍♂️
