### ISSUE TITLE
Dispatcher dynamique

### ISSUE THREAD

**Issue by ghost** [DraftProducts/blagues-api#428]
J'avais eu l'idée de rendre la fonction "register" de la classe "Dispatcher" dynamique pour charger automatiquement les fichiers des commandes... je n'ai aucune idée de comment faire ça, mais dans l'idée ça pourrais être plus propre et plus pratique de faire comme ça, que de devoir continuer à lister toutes les commandes dans le dispatcher…

**Comment by DraftProducts** [comment]
Au vu du nombre de commandes qu'on a je sais pas si ça vaut le coup, mais si on valide le fait de le faire, je suis d'accord de m'en occuper 👍

**Comment by achille-bsc** [comment]
Ouais, c'est vrai qu'on n'a pas beaucoup de commandes... mais à force d'en ajouter ça va finir par faire un certain nombre... et puis je trouve ça toujours un peu plus propre que de devoir tous les citer un à un non ? (après, je dit ça, mais je ne sais pas faire ce genre de handlers... donc si ça se trouve, ce n'est pas du tout le cas...)

**Comment by DraftProducts** [comment]
C'est vrai que t'as raison, c'est plus propre.

**Comment by DraftProducts** [comment]
Je m'en occuperais 👍

**Comment by achille-bsc** [comment]
> Je m'en occuperais 👍

Cool ! j'ai hâte de voir comment tu feras ! ça m'intéresse à fond !
