### ISSUE TITLE
Déplacement de la langue FR dans les localisations

### ISSUE THREAD

**Issue by achille-bsc** [DraftProducts/blagues-api#431]
J'avais pensé à faire en sorte à ce que puisse mettre des nameLocalization sur les commandes, ça permettrais d'avoir les commandes et leurs arguments dans la langue de notre client, ce qui serait peut-être un peu mieux non ? c'est un détail, mais sur ce projet à partir de maintenant, il ne reste plus que les détails à peaufiner, je crois 😅

**Comment by achille-bsc** [comment]
Quitte à ne mettre qu'en français pour le moment et par la suite ajouter l'anglais ou d'autres langues…

**Comment by achille-bsc** [comment]
Et je pense que je serais prêt à le faire, il suffirait de changer quelques types dans la classe Command

**Comment by swiizyy** [comment]
Y'aurais rien a changer dans Command a part dans le get Data retourner les nameLocalisations

**Comment by achille-bsc** [comment]
ouais, enfin je checkerais ça au moment de le faire si l'ajout est validé tkt 😉

**Comment by DraftProducts** [comment]
Pas vraiment convaincu par l'idée, le contenu ainsi que les blagues sont en français.

**Comment by DraftProducts** [comment]
à la limite ce qui pourrait se tenter c'est le nom des commandes + arguments en anglais et une traduction complête en français.
ça permettrait d'utiliser des accents

**Comment by swiizyy** [comment]
> à la limite ce qui pourrait se tenter c'est le nom des commandes + arguments en anglais et une traduction complête en français. ça permettrait d'utiliser des accents

Je crois que c'etait sa le but 🤔

**Comment by DraftProducts** [comment]
D'acc bah perso je suis pour 👍

**Comment by achille-bsc** [comment]
OK 👍  nickel ! Dans ce cas, je lance une pr de suite 🙃

**Comment by achille-bsc** [comment]
si tout le monde est  ok pour valider la PR dites le moi et ensuite on va pouvoir merge 🙃
