### ISSUE TITLE
Utilisation d'un formulaire lors de la proposition d'une blague

### ISSUE THREAD

**Issue by AulysV** [DraftProducts/blagues-api#448]
La proposition d'une blague se fait actuellement _via_ une commande. Discord propose une fonctionnalité qui permet d'envoyer des informations à un bot, à travers un "formulaire" (dont voici un exemple). J'ignore s'il est possible de créer des listes déroulantes pour la sélection du type de blague, mais je pense qu'il est possible d'en définir un après l'envoi.

![image](https://user-images.githubusercontent.com/50235846/200167545-65275be1-f4cb-49e3-84d9-fbb03ffadfc7.png)

**Comment by DraftProducts** [comment]
Pour l'instant ce n'est pas encore possible d'ajouter de sélecteurs aux modals ce qui rend pour l'instant les commandes Slash le meilleur support pour la suggestion de blagues : 
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal
![image](https://user-images.githubusercontent.com/29425008/200180285-a80e41f4-e9ca-4fe1-9395-be28eff27105.png)
 
Le jour où cela sera possible, nous passerons aux modals sans hésiter 👍
