### ISSUE TITLE
Suggestion de suppression

### ISSUE THREAD

**Issue by achille-bsc** [DraftProducts/blagues-api#449]
Ce serait pratique que n'importe qui puisse proposer une blague à retirer de l'api, et comme pour les suggestions de blagues, les parrains pourront approuver ou desaprouver... ça me semble être un bon système pour les blagues qui ont été acceptés il y a un moment alors qu'elles ne le seraient peut-être pas actuellement...

**Comment by DraftProducts** [comment]
On a ajouté la commande `/delete` dans #424 (qui a remplacé l'idée de la commande `/report`) pour ces cas de figure extrêmes, mais selon moi, une fois qu'une blague a été ajoutée, elle n'a pas de raison d'être à nouveau retiré.
Si une discussion dans le salon des parrains voit le jour pour la suppression d'une blague, on le fera, mais en dehors de ce cas de figure, on ne devrait pas avoir à revoir les blagues déjà ajoutées.
