### ISSUE TITLE
L'endpoint blague par ID ne marche pas

### ISSUE THREAD

**Issue by Zuruuh** [DraftProducts/blagues-api#486]
``https://www.blagues-api.fr/api/id/1``
Peut importe l'id, l'api renvoie toujours une 404

**Comment by achille-bsc** [comment]
personnelement je reçoit l'erreur en 401

**Comment by Zuruuh** [comment]
@achille-bsc 401 c'est quand y'a un soucis avec ton token de connexion :smile: check le message dans le body de la response quand tu réessaye.

Je viens de reproduire le soucis est toujours d'actualité :+1:

**Comment by DraftProducts** [comment]
Salut @Zuruuh, tu souhaites t'occuper du fix ?

**Comment by Zuruuh** [comment]
@DraftProducts yes :+1:
